Pos-System-Capstone/Pos-System-Backend

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Controllers/StoreController.cs
- Pos-System/Payload/Response/Stores/GetStoreEmployeesResponse.cs
- Pos-System/Payload/Response/Stores/GetStoreResponse.cs
- Pos-System/Services/Implements/StoreService.cs
- Pos-System/Services/Interfaces/IStoreService.cs
Added API to view store's employees
url: /api/v1/stores/{storeId}/employees
Request (all in parameter):
storeId
searchUsername (Optional)
page
size
Response:
[
{
"role": "SysAdmin",
"username": "string"
},
...
]
> [PST-24] View store employees

- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/StoreController.cs
- Pos-System/Mappers/Stores/StoreMapper.cs
- Pos-System/Payload/Request/Stores/CreateNewStoreRequest.cs
- Pos-System/Payload/Response/Stores/CreateNewStoreResponse.cs
- Pos-System/Services/Implements/StoreService.cs
- Pos-System/Services/Interfaces/IStoreService.cs
Added new API to allow Brand Manager to create a new store
Jira Link: https://pos-system-project.atlassian.net/jira/software/projects/PST/boards/1?selectedIssue=PST-62
Request Body:
{
"shortName": "string",
"email": "user@example.com",
"phone": "string",
"brandId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"address": "string"
}
Response Body:
{
"shortName": "string",
"email": "string",
"phone": "string",
"brandId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"address": "string"
}
> [PST-62] As a brand manager, I want to create a new store

- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/StoreController.cs
- Pos-System/Payload/Request/Stores/UpdateStoreRequest.cs
- Pos-System/Services/Implements/StoreService.cs
- Pos-System/Services/Interfaces/IStoreService.cs
Added API to update store information
(Brand Manager Role)
URL:
api/v1/stores/{id} (PUT method)
request body:
{
"shortName": "string",
"email": "user@example.com",
"phone": "string",
"address": "string"
}
response: 200
> [PST-11] As an Brand Manager, I want to update brand's store information

- Pos-System/Controllers/BrandController.cs
- Pos-System/Services/Implements/AccountService.cs
- Pos-System/Services/Interfaces/IAccountService.cs
Enhance API get account in brand to get all account when there are no role transfers in the parameter
> [PST-105] Enhance to get all accounts in brand

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/StoreController.cs
- Pos-System/Payload/Request/Accounts/UpdateStaffAccountInformationRequest.cs
- Pos-System/Services/Implements/AccountService.cs
- Pos-System/Services/Interfaces/IAccountService.cs
Add new API to allow store managers to update staff information
Endpoint: api/v1/stores//{storeId}/users/{id}
request body:
{
"name": "string"
}
response: Ok message
> [PST-69] As a store manager, I want to update staff information

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/CollectionController.cs
- Pos-System/Enums/CollectionStatus.cs
- Pos-System/Extensions/DependencyServices.cs
- Pos-System/Payload/Response/Collections/GetCollectionDetailResponse.cs
- Pos-System/Services/Implements/CollectionService.cs
- Pos-System/Services/Interfaces/ICollectionService.cs
Added API to view detail of collection and all products along with collection (pagination included)
API endpoint: api/v1/collections/{id}
{
"id": "068eb203-e4b8-4f82-8184-22b13808277b",
"name": "Combo sáng",
"code": "SA01",
"picUrl": null,
"description": null,
"products": {
"size": 10,
"page": 1,
"total": 2,
"totalPages": 1,
"items": [
{
"id": "c1e2ec73-f50d-43f8-bc1a-7cad3a9b946d",
"productName": "Highlands Tra Sen Vang",
"description": "Tra Sen Vang cua Highlands",
"productCode": "HLTSV",
"picUrl": null,
"sellingPrice": 50000
},
{
"id": "74f8fb4b-335b-42d9-ae1f-86ec60f89fcc",
"productName": "Highlands Tra Den Machiato",
"description": "Tra Den Machiato cua Highlands",
"productCode": "HLTĐM",
"picUrl": null,
"sellingPrice": 60000
}
]
}
}
> [PST-91] As a brand admin, I want to view detail of a collection (Collection Management)

- Pos-System/Controllers/CollectionController.cs
- Pos-System/Payload/Request/Collections/UpdateCollectionInformationRequest.cs
- Pos-System/Payload/Response/Collections/GetCollectionDetailResponse.cs
- Pos-System/Services/Implements/CollectionService.cs
- Pos-System/Services/Interfaces/ICollectionService.cs
- Pos-System/Utils/CustomListUtil.cs
Added API to handle Update collection information
Endpoint: /api/v1/collections/068EB203-E4B8-4F82-8184-22B13808277B (PUT)
body: 
{
"name": "Combo Sang",
"code": "SA01",
"picUrl": "asdasd",
"description": "Combo sang nhe nhang ne",
"productIds": [
"76D5EB08-119F-470F-9078-91CF58349B8F",
"C1E2EC73-F50D-43F8-BC1A-7CAD3A9B946D",
"C98463C3-29B0-4158-83EC-938303BBBF20",
"DDFEE3C3-66E2-4CC2-BF02-BF35DECD6468"
]
}
Response: 200 with id 068EB203-E4B8-4F82-8184-22B13808277B
> [PST-93] As a brand admin, I want to update collection information

- Pos-System/Payload/Request/Accounts/UpdateStaffAccountInformationRequest.cs
- Pos-System/Services/Implements/AccountService.cs
> [PST-113] Enhancement API Update Staff Account: Add ability to update password

- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/ProductController.cs
- Pos-System/Enums/ProductSize.cs
- Pos-System/Payload/Request/Products/UpdateProductRequest.cs
- Pos-System/Services/Implements/ProductService.cs
- Pos-System/Services/Interfaces/IProductService.cs
Added API to handle update product information
API endpoint: api/v1/products/{id} (PUT)
Request:
```
{
"name": "Highlands tra sua truyen thông",
"code": "HLTSTT",
"sellingPrice": 80000,
"categoryId": "FC62450A-F54C-441B-8506-9071ADB5E31E",
"historicalPrice": 12000,
"discountPrice": 75000,
"description": "Tra sua truyen thong JL",
"displayOrder": 5,
"size": "M",
"type": "SINGLE",
}
```
Response : Guid
> [PST-125] As a brand admin, I want to update product's information

- Pos-System.Repository/Implement/UnitOfWork.cs
- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/MenuController.cs
- Pos-System/Enums/MenuProductStatus.cs
- Pos-System/Enums/MenuStoreStatus.cs
- Pos-System/Extensions/DependencyServices.cs
- Pos-System/Payload/Request/Menus/CreateNewMenuRequest.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Interfaces/IMenuService.cs
Description:
Added API to create Menu with multiple products, stores
Endpoint:
api/v1/menus (post)
Request body:
```
{
"code": "PVTGVMenu",
"productOfMenu": [
{
"id": "CBACEAB1-1C6D-4A05-ADBF-117539E8E149",
"sellingPrice": 45000,
"discountPrice": 0
},
{
"sellingPrice": 80000,
"discountPrice": 0
},
],
"storeMenuAdditionInformation": [
{
"id": "8E7A11C8-7FD5-4D9D-B31B-65FA2D9E489B",
"priority": 2,
"dateFilter": 0,
"timeFilter": 0
}
]
}
```
Response:
Menu Id
> [PST-129] As a brand admin, I want to create a store's menu

- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/StoreController.cs
- Pos-System/Mappers/Accounts/AccountMapper.cs
- Pos-System/Payload/Request/Accounts/CreateNewStoreAccountRequest.cs
- Pos-System/Payload/Response/Accounts/CreateNewStoreAccountResponse.cs
- Pos-System/Services/Implements/AccountService.cs
- Pos-System/Services/Interfaces/IAccountService.cs
```
Enhance the API to create an account
request:
{
name: "string",
username: "string",
password: "string"
}
```
> [PST-25] Enhance Create Store Account api to create store manager

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/CategoryController.cs
- Pos-System/Controllers/ProductController.cs
- Pos-System/Enums/ProductType.cs
- Pos-System/Services/Implements/CategoryService.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Implements/ProductService.cs
- Pos-System/Services/Interfaces/ICategoryService.cs
- Pos-System/Services/Interfaces/IProductService.cs
Description: [API] Add API to add extra categories to product categories
Endpoint: api/v1/categories/extra-categories(POST)
Request body: 
```
[
"asfasnasasnvlasvnaslvnaslvksav",
"asdasdsadsadasdnasdsafsaposv"
]
```
Description: [API] Add API to view list extra categories of categories
Endpoint: api/v1/categories/{categoriesId}/extra-categories(Get)
> [API] Add API to add extra categories to product categories

- Pos-System/Payload/Response/Accounts/GetAccountResponse.cs
- Pos-System/Services/Implements/AccountService.cs
Enhance API Get Account detail make it response along with storeId and brandId
Will return storeId and brandId for account role: Staff and Store Manager
StoreId will return null if account Role is: Brand Admin and Brand Manager
> [PST-146] Enhance API get account to response store and brand ID

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/MenuController.cs
- Pos-System/Payload/Request/Menus/UpdateMenuProductsRequest.cs
- Pos-System/Services/Implements/CategoryService.cs
- Pos-System/Services/Implements/CollectionService.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Interfaces/IMenuService.cs
- Pos-System/Utils/CustomListUtil.cs
Added API to handle add/update menu's products
endpoint: api/v1/menus/{menuId}/products (POST)
request body:
```
{
"products": [
{
"productId": "2799957C-1276-46C0-9513-AE01A837B1C1",
"sellingPrice": 33000,
"discountPrice": 0
},
{
"productId": "EF7C9479-9CFD-4E16-8161-3C174FCCB8E5",
"sellingPrice": 32000,
"discountPrice": 5000
},
{
"productId": "FBA7CE7A-DEB1-4FB1-AF3B-2386628324CA",
"sellingPrice": 32000,
"discountPrice": 5000
}
]
}
```
response: updated menu Id
> [PST-147] As a brand admin, I want to update the store's menu (product, price, status of menu)

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/MenuController.cs
- Pos-System/Payload/Response/Menus/GetMenuDetailResponse.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Interfaces/IMenuService.cs
Added API for brand admin get menu detail
endpoint: api/v1/brands/{id}/menus/{menuId} (GET)
response:
```C#
{
"priority": 0,
"isBaseMenu": true,
"dateFilter": [
"Sunday"
],
"startTime": "13:45:42.0000000",
"endTime": "13:45:42.0000000",
"createdBy": "string",
"createdAt": "2023-02-28T07:12:50.712Z",
"updatedBy": "string",
"updatedAt": "2023-02-28T07:12:50.712Z",
"products": [
{
"sellingPrice": 0,
"discountPrice": 0,
"historicalPrice": 0,
"type": "SINGLE",
"categoryName": "string",
"createdBy": "string",
"createdAt": "2023-02-28T07:12:50.712Z",
"updatedBy": "string",
"updatedAt": "2023-02-28T07:12:50.712Z"
}
],
"stores": [
{
"id": …
```
> PST-139: Api for brand admin get menu detail

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/MenuController.cs
- Pos-System/Payload/Response/Menus/GetMenuDetailForStaffResponse.cs
- Pos-System/Pos-System.API.csproj
- Pos-System/Services/BaseService.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Implements/ProductService.cs
- Pos-System/Services/Interfaces/IMenuService.cs
Added API for staff to get menu products
endpoint: api/v1/menus/staff/products (GET)
request: None
response:
```
{
"brandId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"priority": 0,
"isBaseMenu": true,
"dateFilter": [
"Sunday"
],
"startTime": "13:45:42.0000000",
"endTime": "13:45:42.0000000",
"products": [
{
"sellingPrice": 0,
"picUrl": "string",
"historicalPrice": 0,
"discountPrice": 0,
"description": "string",
"displayOrder": 0,
"size": "string",
"type": "SINGLE",
"parentProductId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"brandId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"categoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6", …
```
> [PST-144] As an staff, I want to read menu detail

- Pos-System/Controllers/MenuController.cs
- Pos-System/Payload/Response/Products/GetProductInMenuResponse.cs
- Pos-System/Pos-System.API.csproj
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Interfaces/IMenuService.cs
API for brand admin get list product in menu (paging included, filter by product Name)
Endpoint: api/v1/menu/{menuId}/product (GET)
Response:
```C#
{
"size": 0,
"page": 0,
"total": 0,
"totalPages": 0,
"items": [
{
"sellingPrice": 0,
"picUrl": "string",
"historicalPrice": 0,
"discountPrice": 0
}
]
}
```
> PST-148: As a brand admin, I want to view list product in menu

- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/MenuController.cs
- Pos-System/Payload/Request/Menus/UpdateMenuInformationRequest.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Interfaces/IMenuService.cs
Api for brand admin update menu information
Endpoint: api/v1/menus/{menuId} (PUT)
Request body:
```C#
{
"priority": 0,
"dateFilter": 0,
"startTime": 1439,
"endTime": 1439
}
```
Response: 
<pre>Success: 200 ok with message
Failed: 400 bad request with message
> PST-151: As a brand admin, I want to update menu information

- Pos-System.Domain/Models/PaymentType.cs
- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/OrderController.cs
- Pos-System/Enums/OrderPaymentType.cs
- Pos-System/Enums/OrderStatus.cs
- Pos-System/Enums/OrderType.cs
- Pos-System/Extensions/DependencyServices.cs
- Pos-System/Payload/Request/Orders/CreateNewOrderRequest.cs
- Pos-System/Services/Implements/OrderService.cs
- Pos-System/Services/Interfaces/IOrderService.cs
- Pos-System/Utils/TimeUtils.cs
Added API to create Order
Endpoint: api/v1/stores/{storeId}/orders
Request
```JSON
{
"payment": "CASH",
"orderType": "IN_STORE",
"productsList": [
{
"productInMenuId": "55BFE53D-6D4E-4A9B-8837-7663D298E55C",
"quantity": 2,
"sellingPrice": 39000,
"note": "string",
"extras": [
{
"productInMenuId": "26AB39DA-9EFA-4DC7-9B9F-81FDC528593D",
"quantity": 3,
"sellingPrice": 5000
}
]
},
{
"productInMenuId": "76487AB9-1461-41DD-8B48-B6AD2A00B37C",
"quantity": 1,
"sellingPrice": 23000,
"note": "string",
"extras": [
]
}
],
"totalAmount": 272000,
"discountAmount": 0,
"vat": 10,
"vatAmount": 27200,
"finalAmount": 299200
}
```
Response: OrderId
> [PST-152] As a staff, I want to create a order

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/OrderController.cs
- Pos-System/Payload/Response/Menus/GetMenuDetailForStaffResponse.cs
- Pos-System/Payload/Response/Orders/GetOrderDetailResponse.cs
- Pos-System/Services/Implements/OrderService.cs
- Pos-System/Services/Implements/StoreService.cs
- Pos-System/Services/Interfaces/IOrderService.cs
Added API to get the order details and fix others API minor issues
Endpoint: api/v1/store/{storeId}/orders/{id} GET
Response:
Ex: api/v1/store/{8E7A11C8-7FD5-4D9D-B31B-65FA2D9E489B}/orders/{424C1724-EDBB-489E-885E-570DB3E9AFDB}
```JSON
{
"orderId": "424c1724-edbb-489e-885e-570db3e9afdb",
"invoiceId": "PPVT202303071351342132",
"totalAmount": 272000,
"finalAmount": 299200,
"vat": 10,
"vatAmount": 27200,
"discount": 0,
"orderStatus": "PENDING",
"orderType": "EAT_IN",
"checkInDate": "2023-03-07T13:51:34.2132842",
"payment": {
"id": "4758c635-2a33-4c39-92ed-42ff472416d3",
"paymentTypeId": "88ffcc6a-ae89-410e-b496-f26673276727",
"paymentType": "CASH",
"picUrl": null,
"paidAmount": 299200
},
"productList": [
{
"productInMenuId": "76487ab9-1461-41dd-8b48-b6ad2a00b37c",
"orderDetailId": …
```
> [PST-42] As a staff, I want to read the order in detail

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Controllers/MenuController.cs
- Pos-System/Payload/Request/Menus/UpdateStoresApplyMenuRequest.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Interfaces/IMenuService.cs
Api for brand admin view list store apply menu and update store list apply menu
Endpoint:  api/v1/menus/{menuId}/stores (GET/POST)
Request: for update store list apply menu
```JSON
{
"storeIds": [
"3fa85f64-5717-4562-b3fc-2c963f66afa6"
]
}
```
Response:
menuId with status 200
```JSON
"3fa85f64-5717-4562-b3fc-2c963f66afa6" for example
```
Response: for get list store apply menu:
```JSON
{
"size": 0,
"page": 0,
"total": 0,
"totalPages": 0,
"items": [
{
"brandId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"shortName": "string",
"email": "string",
"address": "string",
"phone": "string",
"code": "string"
}
]
}
```
> PST-131: As a brand admin, I want to update store apply menu

- Pos-System/Controllers/OrderController.cs
- Pos-System/Enums/OrderStatus.cs
- Pos-System/Payload/Request/Orders/CreateNewOrderRequest.cs
- Pos-System/Payload/Request/Orders/UpdateOrderRequest.cs
- Pos-System/Services/Implements/OrderService.cs
- Pos-System/Services/Interfaces/IOrderService.cs
Added API to update Order Status and Payment
Endpoint: api/v1/stores/{storeId}/orders/{id} PUT
Payload: 
```JSON
{
"status": "PENDING",
"payment": "CASH"
}
```
Response: orderId
> [PST-162] API for Updating an Order payment and Status

- Pos-System/Services/Implements/MenuService.cs
Fix api add/remove products in store's menu
Endpoint: api/v1/menus/{menuId}/products (POST)
Request :
```JSON
{
"products": [
{
"productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"sellingPrice": 0,
"discountPrice": 0
}
]
}
```
Response:
Status 200 with menuId
```JSON
"3fa85f64-5717-4562-b3fc-2c963f66afa6" for example
```
> PST-164: Fix api add/remove products in store's menu

- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/OrderController.cs
- Pos-System/Payload/Request/Menus/CreateNewMenuRequest.cs
- Pos-System/Services/Implements/AccountService.cs
- Pos-System/Services/Implements/MenuService.cs
Enhanced API Create new menu let it able to create a menu with products in Base Menu
Endpoint: api/v1/menus
Request:
```JSON
{
"priority": 0,
"dateFilter": 0,
"startTime": 1439,
"endTime": 1439,
"isBaseMenu": true,
"isUseBaseMenu": true
}
```
> [PST-176] Enhance create new menu, add field useBaseMenu to apply current products in base menu to new menu

- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/MenuController.cs
- Pos-System/Payload/Request/Menus/UpdateMenuStatusRequest.cs
- Pos-System/Services/Implements/AccountService.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Implements/StoreService.cs
- Pos-System/Services/Interfaces/IMenuService.cs
Added API to update menu status
Endpoint: api/v1/menu/{menuId}
request: 
```JSON
{
"op": "string",
"path": "string",
"value": "string"
}
```
> [PST-178] As a brand admin, I want to change status of store's menu

- Pos-System/Controllers/StoreController.cs
- Pos-System/Services/Implements/OrderService.cs
Api endpoint: api/v1/stores/{storeId}/orders (GET)
Paging included
Filter by StartDate, EndDate, OrderType, Status
Role added: staff
Response:
```C#
{
"size": 0,
"page": 0,
"total": 0,
"totalPages": 0,
"items": [
{
"invoiceId": "string",
"staffName": "string",
"startDate": "2023-03-29T04:54:12.604Z",
"endDate": "2023-03-29T04:54:12.604Z",
"finalAmount": 0,
"orderType": "EAT_IN",
"status": "PENDING"
}
]
}
```
> Pst-182: Api for staff get list order of store (descending by checkInDate)

- Pos-System.Domain/Models/GroupProduct.cs
- Pos-System.Domain/Models/PosSystemContext.cs
- Pos-System.Domain/Models/Product.cs
- Pos-System.Domain/Models/ProductInGroup.cs
- Pos-System.Domain/Models/Session.cs
- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/StoreController.cs
- Pos-System/Extensions/DependencyServices.cs
- Pos-System/Payload/Request/Sessions/CreateStoreSessionsRequest.cs
- Pos-System/Payload/Response/Sessions/GetStoreSessionListResponse.cs
- Pos-System/Payload/Response/Stores/GetStoreEndShiftStatisticsResponse.cs
- Pos-System/Pos-System.API.csproj
- Pos-System/Services/Implements/OrderService.cs
- Pos-System/Services/Implements/SessionService.cs
- Pos-System/Services/Implements/StoreService.cs
- Pos-System/Services/Interfaces/ISessionService.cs
- Pos-System/Services/Interfaces/IStoreService.cs
- Pos-System/Utils/TimeUtils.cs
Added 3 news API to handle Session
Added GroupProduct, ProductInGroup Models,
Added Name column to Session Table,
Order Logic Changes
**Create new store Session: (Store Manager Only)**
**Get Store Session List (Store Manager & Staff)**
Request:
Response:
**Get store Session Statictis:  (Store Manager & Staff)**
Request:
Response:
> [PST-184-185-186] Session Function, Database Update, Order Logic Fix

- Pos-System.Domain/Models/GroupProduct.cs
- Pos-System.Domain/Models/PosSystemContext.cs
- Pos-System.Domain/Models/ProductInGroup.cs
- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/ProductController.cs
- Pos-System/Enums/GroupCombinationMode.cs
- Pos-System/Enums/GroupProductStatus.cs
- Pos-System/Enums/ProductInGroupStatus.cs
- Pos-System/Enums/ProductType.cs
- Pos-System/Payload/Request/Products/CreateNewGroupProductRequest.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Implements/OrderService.cs
- Pos-System/Services/Implements/ProductService.cs
- Pos-System/Services/Interfaces/IProductService.cs
- Pos-System/Utils/TimeUtils.cs
Added API to create Group Product,
Fix Timezone Issue,
Fix order for get product in menu and product in brand
Request:
> [PST-187] Added API to create Group Product, fix some issues

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/ProductController.cs
- Pos-System/Payload/Request/Products/CreateNewGroupProductRequest.cs
- Pos-System/Payload/Request/Products/UpdateGroupProductRequest.cs
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Implements/ProductService.cs
- Pos-System/Services/Implements/SessionService.cs
- Pos-System/Services/Interfaces/IProductService.cs
Added API to Update Group Product, Fix Session time issue
Request: (Proucts field is optional, if no provied, ProductInGroup not change anything)
Response: (Guid)
> [PST-188] Added API to Update Group Product, Fix Session time issue

- Pos-System/Constants/MessageConstant.cs
- Pos-System/Services/Implements/StoreService.cs
Enhance the get menu detail for staff to get a menu with the highest priority and menu in the time required
> [NO JIRA] Enhance Get Menu Detail For Staff

- Pos-System/Controllers/StoreController.cs
- Pos-System/Payload/Request/Sessions/UpdateStoreSessionRequest.cs
- Pos-System/Services/Implements/SessionService.cs
- Pos-System/Services/Interfaces/ISessionService.cs
Added API to update store session
name (optional)
cashInitInVault (optional) 
Request:
> [PST-191] As a store manager, I want to update sessions of a store

- Pos-System/Constants/ApiEndPointConstant.cs
> Hot fix endpoint for Session

- Pos-System/Constants/MessageConstant.cs
- Pos-System/Services/Implements/SessionService.cs
Fixed logic when creating or update session that make duplicate session
> [NO JIRA] Fixed duplicated session when create or update

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Controllers/ProductController.cs
- Pos-System/Payload/Response/Products/GetGroupProductListResponse.cs
- Pos-System/Services/Implements/ProductService.cs
- Pos-System/Services/Interfaces/IProductService.cs
Added API to get GroupProduct for combo Product type
Request: 
Response:
> [PST-192] Added API to get GroupProduct for combo Product type

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Controllers/CategoryController.cs
- Pos-System/Controllers/ProductController.cs
- Pos-System/Payload/Response/Categories/GetProductsInCategory.cs
- Pos-System/Payload/Response/Menus/GetMenuDetailForStaffResponse.cs
- Pos-System/Services/Implements/CategoryService.cs
- Pos-System/Services/Implements/StoreService.cs
- Pos-System/Services/Interfaces/ICategoryService.cs
Added API to get products in category
Enhance API get menu for staff to get groupProduct and productInGroup
Request category:
Response category:
Response menu for staff:
> [PST-193] API: Enhance API get menu for staff

- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Constants/MessageConstant.cs
- Pos-System/Controllers/ProductController.cs
- Pos-System/Payload/Request/Products/UpdateProductInGroupRequest.cs
- Pos-System/Services/Implements/ProductService.cs
- Pos-System/Services/Interfaces/IProductService.cs
Added API to update single product in group
Request:
Response: Id
> [PST-194] API: Handle API to update single product in group

- Pos-System.Domain/Models/Brand.cs
- Pos-System.Domain/Models/Order.cs
- Pos-System.Domain/Models/PosSystemContext.cs
- Pos-System.Domain/Models/Product.cs
- Pos-System.Domain/Models/Promotion.cs
- Pos-System.Domain/Models/PromotionOrderMapping.cs
- Pos-System.Domain/Models/PromotionProductMapping.cs
- Pos-System/Constants/ApiEndPointConstant.cs
- Pos-System/Controllers/StoreController.cs
- Pos-System/Enums/PromotionEnums.cs
- Pos-System/Extensions/DependencyServices.cs
- Pos-System/Payload/Request/Orders/CreateNewOrderRequest.cs
- Pos-System/Payload/Response/Orders/GetOrderDetailResponse.cs
- Pos-System/Payload/Response/Promotion/GetPromotionResponse.cs
- Pos-System/Payload/Response/Stores/GetStoreEndDayReport.cs
- Pos-System/Pos-System.API.csproj
- Pos-System/Properties/launchSettings.json
- Pos-System/Services/Implements/MenuService.cs
- Pos-System/Services/Implements/OrderService.cs
- Pos-System/Services/Implements/ReportService.cs
- Pos-System/Services/Interfaces/IOrderService.cs
- Pos-System/Services/Interfaces/IReportService.cs
> Promotion update
